stages:
  - test
  - build
  - deploy
  
variables:
  DOCKER_REGISTRY: "yueting"
  DOCKER_IMAGE_NAME: "my-nodejs-example"
  DOCKER_IMAGE_TAG: "1"

test:
  stage: test
  image: node:alpine
  script:
   - npm install
   - npm test
  tags:
   - dev

build:
  stage: build
  image: docker:latest
  script:
   - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
   - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
   - echo "finish"
  tags:
   - dev
  when: manual
   
deploy:
  stage: deploy
  image: alpine:3.6
  script:
   - apk add --update
   - apk add curl
   - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
   - chmod +x ./kubectl
   - mv ./kubectl /usr/local/bin/kubectl
   - mkdir -p $HOME/.kube
   - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
   - chown $(id -u):$(id -g) $HOME/.kube/config
   #- modify docker image tag
   - kubectl replace -f example.yaml
   - echo "finish"
  tags:
   - dev
  when: manual
