kind: PersistentVolume
apiVersion: v1
metadata:
  name: k8s-cer
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/k8s_cer
    server: 192.168.10.1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: k8s-cer-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
