concurrent = 1
check_interval = 0

[[runners]]
  name = "8fe16152990c"
  url = "https://gitlab.com/ci"
  token = "***************"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    network_mode = "host"
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/etc/kubernetes/admin.conf:/etc/kubernetes/admin.conf", "/etc/docker/daemon.json:/etc/docker/daemon.json", "/cache"]
    shm_size = 0
  [runners.cache]
